import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Knotic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <h1 className="hidden">Knotic</h1>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <p>Copyright 2026 Knotic</p>
        </footer>
      </body>
    </html>
  );
}
